version: "3.3"

services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    ports: 
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: "postgres"
    healthcheck:
      test: "exit 0"
  service:
    build: service/
    volumes:
      - .:/code
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    depends_on:
      db:
        condition: service_healthy
    command: python3 /code/service/main.py